### ISSUE TITLE
Delete account from pancake.io?

### ISSUE THREAD

**Issue by schallermarc** [pancakeio/pk#1]
Hi,

I found nowhere else to ask you where I can delete my account from pancake.io? Nice project, congrats!

Best regard,
Marc

**Comment by octavore** [comment]
Hi Marc, there's an option at the bottom of the settings page where you can click to deactivate your account. Hope that helps!

**Comment by schallermarc** [comment]
Thank you,


Sorry for inconvenience,


Best regards,
Marc
